# Generated by Django 5.2.7 on 2025-10-13 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_fake',
        ),
    ]
