# Generated by Django 5.2.7 on 2025-10-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_remove_product_is_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='배송비'),
        ),
    ]
