# Generated by Django 5.2.7 on 2025-10-14 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('is_reported', models.BooleanField(default=False, verbose_name='신고됨')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop_app.product', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(choices=[('product', '상품 문의'), ('shipping', '배송 문의'), ('exchange', '교환/반품'), ('other', '기타')], max_length=20, verbose_name='문의 유형')),
                ('title', models.CharField(max_length=200, verbose_name='문의 제목')),
                ('content', models.TextField(verbose_name='문의 내용')),
                ('email', models.EmailField(max_length=254, verbose_name='답변 받을 이메일')),
                ('answer', models.TextField(blank=True, verbose_name='답변 내용')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='답변일')),
                ('is_answered', models.BooleanField(default=False, verbose_name='답변완료')),
                ('is_reported', models.BooleanField(default=False, verbose_name='신고됨')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='shop_app.product', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '문의',
                'verbose_name_plural': '문의들',
                'ordering': ['-created_at'],
            },
        ),
    ]
