# Generated by Django 5.2.7 on 2025-10-14 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_comment_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='이미지')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='대체 텍스트')),
                ('is_primary', models.BooleanField(default=False, verbose_name='대표 이미지')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop_app.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '상품 이미지',
                'verbose_name_plural': '상품 이미지들',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
