# Generated by Django 5.2.7 on 2025-10-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/detail/', verbose_name='상세 설명 이미지'),
        ),
    ]
