# Generated by Django 5.2.7 on 2025-10-13 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_app', '0002_remove_product_is_fake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='총 금액')),
                ('status', models.CharField(choices=[('pending', '결제 대기'), ('paid', '결제 완료'), ('shipped', '배송 중'), ('delivered', '배송 완료'), ('cancelled', '주문 취소')], default='pending', max_length=20, verbose_name='주문 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='주문일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('shipping_name', models.CharField(max_length=100, verbose_name='받는 사람')),
                ('shipping_address', models.TextField(verbose_name='배송 주소')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='주문자')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='단가')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='주문')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '주문 상품',
                'verbose_name_plural': '주문 상품들',
            },
        ),
    ]
